# Generated by Django 3.0.3 on 2020-02-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(max_length=30)),
                ('source', models.IntegerField()),
                ('destination', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideservice.Ride')),
            ],
            options={
                'unique_together': {('username', 'ride_id')},
            },
        ),
    ]
