# Generated by Django 3.0.2 on 2020-01-26 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('source', models.IntegerField()),
                ('destination', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User_rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.Ride')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.User')),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.User'),
        ),
    ]
