# Generated by Django 3.0.2 on 2020-01-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='timestamp',
            field=models.CharField(max_length=30),
        ),
    ]
