# Generated by Django 3.0.2 on 2020-01-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0002_auto_20200126_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='created_by',
            field=models.CharField(max_length=50),
        ),
    ]
