# Generated by Django 3.0.2 on 2020-01-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0004_auto_20200127_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='created_by',
            new_name='username',
        ),
    ]
