# Generated by Django 3.0.2 on 2020-01-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0005_auto_20200127_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rideshare.User'),
        ),
    ]
