# Generated by Django 3.0.2 on 2020-01-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0006_auto_20200127_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='username',
            new_name='created_by',
        ),
    ]
