# Generated by Django 3.0.2 on 2020-01-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0007_auto_20200127_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='timestamp',
            field=models.DateTimeField(max_length=30),
        ),
    ]
