# Generated by Django 3.0.2 on 2020-01-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0008_auto_20200127_2212'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_rides',
            unique_together={('username', 'ride_id')},
        ),
    ]
