version: '3'

services:
  rides:

    container_name: rides
    image: rides:latest
    restart: always
    volumes:
      - /home/ubuntu/Rides:/rideshare
    environment:
      - TEAM_NAME=CC_0275_0950_1346_1633 
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80" 
    ports:
      - "80:80"

  